name: 'Sonar Analysis'
description: 'Run SonarQube and SonarCloud analysis'

runs:
  using: "composite"
  steps:
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: $SONAR_TOKEN