name: 'Sonar Analysis'
description: 'Run SonarQube and SonarCloud analysis'

inputs:
  project-key:
    description: 'Sonar project key'
    required: true
  organization:
    description: 'SonarCloud organization'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: $SONAR_TOKEN

    - name: Analyze with SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2.2.0
      env:
        SONAR_TOKEN: $SONAR_TOKEN 
      with:
        args:
          -Dsonar.projectKey=${{ inputs.project-key }}
          -Dsonar.organization=${{ inputs.organization }}
        projectBaseDir: .