name: 'Sonar Analysis'
description: 'Run SonarQube and SonarCloud analysis'

inputs:
  project-key:
    description: 'Sonar project key'
    required: true
  organization:
    description: 'SonarCloud organization'
    required: false

runs:
  using: "composite"
  steps:
    - name: Analyze with SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2.2.0
      env:
        SONAR_TOKEN: $SONAR_TOKEN 
      with:
        args:
          -Dsonar.projectKey=${{ inputs.project-key }}
          -Dsonar.organization=${{ inputs.organization }}
        projectBaseDir: .