name: 'Trivy Security Scanner'
description: 'Scan container images for vulnerabilities using Trivy'

runs:
  using: "composite"
  steps:
    - name: Build an image from Dockerfile
      shell: bash
      run: docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      with:
        image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
