name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  cicd-pipeline:
    uses: ./.github/workflows/template.yml
    with:
      environment: dev
      aws-region: ap-southeast-2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}