# name: Dev CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   cicd-pipeline:
#     uses: ./.github/workflows/template.yml
#     permissions: 
#       security-events: write
#     with:
#       environment: dev
#       aws-region: ap-southeast-2
#     secrets:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args:
            -Dsonar.projectKey=JunTran2137_CICD-Project
            -Dsonar.organization=juntran2137
          projectBaseDir: .